'''This python program takes a gcode generated by Cura and renames the file with the format: xxHxxM

Made by Julian Caro Linares, jcarolinares@gmail.com

'''

import os
import re

route= raw_input("Selecciona directorio a renombrar:\n")

route=str(route)

files_list=os.listdir(route)

for gcode_file in files_list:
    if re.search('.gcode',gcode_file):
        print (gcode_file)

        #Reading the file
        file=open(gcode_file,'r')
        file_string=file.read()
        file.close()

        string_time=re.search(';Print time: (.+?)minutes',file_string)

        if string_time:
            file_string= string_time.group()

        print (file_string)

        file_string=file_string.replace(';Print time: ','')
        file_string=file_string.replace(' hour ','h')
        file_string=file_string.replace(' hours ','h')
        file_string=file_string.replace(' minutes','m')
        file_string=file_string.replace(' minute','m')

        print (file_string)

        new_file_name=file_string+'-'+gcode_file

        print (new_file_name)

        #Time to rename the file
        os.rename(gcode_file, gcode_file.replace(gcode_file, new_file_name))







'''
for fileName in os.listdir("."):

    os.rename(fileName, fileName.replace(file_name, new_file_name))
'''
#no2data=no2data.replace("-","0")#Replaces no data with a 0
