#!/usr/bin/python

'''This python program takes a gcode generated by Cura and renames the file with the format: xxHxxM

Made by Julian Caro Linares, jcarolinares@gmail.com

'''

import os
import re
import sys
import gcoder

#import pdb #Debug library, use pdb.set_trace() in the point that you want to see



route="."
counter=0
after_name=False #Controls the order of the name: XXhXXm-name_file.gcode or name_file-XXhXXm.gcode
cost_of_print=False #Controls the cost of print option
print_cost_list=[] #A list with all the cost of print of each object
total_cost=0 #Total cost of all the objects

#Terminal parameter
if __name__ == '__main__':

    #print(len(sys.argv))

    if len(sys.argv) == 1:
        route="."
    elif len(sys.argv) == 2 and sys.argv[1]=="-after":
        after_name=True
        route ="."
    elif len(sys.argv) == 3 and sys.argv[1]=="-after":
        after_name=True
        route = sys.argv[2]
    elif len(sys.argv) == 2 and sys.argv[1]=="-cost":
        cost_of_print=True
        route = "."
    elif len(sys.argv) == 3 and sys.argv[1]=="-cost":
        cost_of_print=True
        route = sys.argv[2]

    else:
        route = sys.argv[1]
    #print route


#route= raw_input("Select path:\n")
route=str(route)

files_list=os.listdir(route)

#for x in files_list:
#    print x

for gcode_file in files_list:
    if re.search('\.gcode',gcode_file):
        #print (route+gcode_file)

        #Reading the file
        if route==".":
            file=open(gcode_file,'a+')
        else:
            file=open(route+gcode_file,'a+')


        file_string=file.read()


        if not re.search('; -- renamed with printing_time_file.py',file_string): #If file hasn't been renamed before

            counter=counter+1

            string_time_cura=re.search(';Print time: (.+?)minutes',file_string)
            string_time_simplify=re.search(';   Build time: (.+?) min',file_string)
            string_cost_cura=re.search(';Filament cost: (.+?)\n',file_string)
            string_cost_simplify=re.search(';   Material cost: \$(.+?) ',file_string)

            if string_time_cura:

                file_string= string_time_cura.group()

                #print (file_string)
                file_string=file_string.replace(';Print time: ','')
                file_string=file_string.replace(' hour ','h')
                file_string=file_string.replace(' hours ','h')
                file_string=file_string.replace(' minutes','m')
                file_string=file_string.replace(' minute','m')

                #Cost of printing
                #;Filament cost: 0.35 #cura gcode comment
                if cost_of_print==True:

                    if string_cost_cura:
                        print_cost=string_cost_cura.group()
                        print_cost=print_cost.replace(';Filament cost: ','')

                        if "None" in gcode_file:
                            print("The file "+gcode_file+" doesn't have an estimated price")
                        else:
                            print_cost=float(print_cost)
                            print_cost_list.append(print_cost)#Add the price to the files costs list

                if not re.search('; -- renamed with printing_time_file.py',file_string): #If file hasn't been renamed before
                    file.write("\n; -- renamed with printing_time_file.py - More info in https://github.com/jcarolinares/printingtimefilegcode")
                    file.close()


            elif string_time_simplify:

                file_string=string_time_simplify.group()
                file_string=file_string.replace(';   Build time: ','')
                #file_string=file_string.replace(' hour ','h')
                #file_string=file_string.replace(' hours ','h')
                file_string=file_string.replace(' min','m')
                file_string=file_string.replace('.','_')

                if cost_of_print==True:
                    #pdb.set_trace()
                    if string_cost_simplify:
                        print_cost=string_cost_simplify.group()
                        print_cost=print_cost.replace(';   Material cost: $','')

                        if "None" in gcode_file:
                            print("The file "+gcode_file+" doesn't have an estimated price")
                        else:
                            print_cost=float(print_cost)
                            print_cost_list.append(print_cost)#Add the price to the files costs list


                if not re.search('; -- renamed with printing_time_file.py',file_string): #If file hasn't been renamed before
                    file.write("\n; -- renamed with printing_time_file.py - More info in https://github.com/jcarolinares/printingtimefilegcode")
                    file.close()

            else: #Slic3r or others
                if route==".":
                    gcode = gcoder.GCode(open(gcode_file, "rU"))
                else:
                    gcode = gcoder.GCode(open(route+gcode_file, "rU"))

                #print "Estimated duration: %s" % gcode.estimate_duration()[1]
                #Estimated duration: 0:45:02
                file_string=str(gcode.estimate_duration()[1])
                file_string=file_string.replace(':','h',1)
                file_string=file_string.replace(':','m',1)

                if not re.search('; -- renamed with printing_time_file.py',file_string): #If file hasn't been renamed before
                    file.write("\n; -- renamed with printing_time_file.py - More info in https://github.com/jcarolinares/printingtimefilegcode")
                    file.close()

                #print file_string

                #file_string="0h0m"

            if after_name==False:
                new_file_name=file_string+'-'+gcode_file
            else:
                line_string=gcode_file.split(".")
                new_file_name=line_string[0]+'-'+file_string+'.'+line_string[1]


            #print (new_file_name)

            #Time to rename the file
            if route==".":
                os.rename(gcode_file, gcode_file.replace(gcode_file, new_file_name))
            else:
                os.rename(route+gcode_file, route+gcode_file.replace(gcode_file, new_file_name))


#Cost sum
if cost_of_print==True:
    total_cost=sum(print_cost_list)

#Finish message
if counter==0:
    print("\nScript complete, not renamed gcode files not found\n")

else:
    print ("\nScript complete: "+str(counter)+" gcode files renamed\n")
    if cost_of_print==True:
        print("Total cost of "+str(counter)+" renamed files: "+str(total_cost)+" $")
