'''This python program takes a gcode generated by Cura and renames the file with the format: xxHxxM

Made by Julian Caro Linares, jcarolinares@gmail.com

'''

import os
import re

file_name='test.gcode'

#Reading the file
file=open(file_name,'r')
file_string=file.read()
file.close()

string_time=re.search(';Print time: (.+?)minutes',file_string)


if string_time:
    file_string= string_time.group()

print (file_string)

file_string=file_string.replace(';Print time: ','')
file_string=file_string.replace(' hour ','h')
file_string=file_string.replace(' minutes','m')

print (file_string)

new_file_name=file_string+'-'+file_name

print (new_file_name)

#Time to rename the file

for fileName in os.listdir("."):
    os.rename(fileName, fileName.replace(file_name, new_file_name))

#no2data=no2data.replace("-","0")#Replaces no data with a 0
